var pageNavigationUI = function() {
this.rendering = function(poPage) {
var voCtl = null;
poPage.canvas.backgroundColor = null;
poPage.canvas.backgroundRepeat = null;
poPage.canvas.backgroundPosition = null;
poPage.canvas.focusBorderColor = null;
poPage.canvas.focusBorderStyle = null;
poPage.canvas.contextMenuId = null;
poPage.canvas.horizontalAlign = null;
poPage.canvas.width = 346;
poPage.canvas.height = 31;
poPage.canvas.refresh();
voCtl = poPage.canvas.createControl("group","grpPrevs",8,4,34,26);
voCtl.tabIndex = 0;
voCtl.zIndex = 0;
voCtl.borderWidth = 0;
{
var voCtl_InnerCtl = null;
voCtl_InnerCtl = poPage.canvas.createControl("image","imgBtnPrev",19,5,15,15);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.zIndex = 0;
voCtl_InnerCtl.src = "/style/image/icon_prev.gif";
voCtl_InnerCtl.borderWidth = 0;
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.onclick = function(e) { page.onClick_imgBtnPrev(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("image","imgBtnPrevEnd",0,5,15,15);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.zIndex = 1;
voCtl_InnerCtl.src = "/style/image/icon_prev10.gif";
voCtl_InnerCtl.borderWidth = 0;
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.onclick = function(e) { page.onClick_imgBtnPrevEnd(e); };
voCtl.addChild(voCtl_InnerCtl);
}
poPage.canvas.appendControl(voCtl);
voCtl = poPage.canvas.createControl("group","grpNexts",301,3,34,26);
voCtl.tabIndex = 0;
voCtl.zIndex = 1;
voCtl.borderWidth = 0;
voCtl.borderStyle = "none";
{
var voCtl_InnerCtl = null;
voCtl_InnerCtl = poPage.canvas.createControl("image","imgBtnNext",0,5,15,15);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.zIndex = 0;
voCtl_InnerCtl.src = "/style/image/icon_next.gif";
voCtl_InnerCtl.borderWidth = 0;
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.onclick = function(e) { page.onClick_imgBtnNext(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("image","imgBtnNextEnd",18,5,15,15);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.zIndex = 1;
voCtl_InnerCtl.src = "/style/image/icon_next10.gif";
voCtl_InnerCtl.borderWidth = 0;
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.borderStyle = "none";
voCtl_InnerCtl.onclick = function(e) { page.onClick_imgBtnNextEnd(e); };
voCtl.addChild(voCtl_InnerCtl);
}
poPage.canvas.appendControl(voCtl);
voCtl = poPage.canvas.createControl("group","grpNumbres",50,3,243,26);
voCtl.tabIndex = 0;
voCtl.zIndex = 2;
voCtl.borderWidth = 0;
voCtl.borderStyle = "none";
{
var voCtl_InnerCtl = null;
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum1",0,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.zIndex = 0;
voCtl_InnerCtl.value = "1";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum1(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum2",25,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.zIndex = 1;
voCtl_InnerCtl.value = "2";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum2(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum3",50,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.zIndex = 2;
voCtl_InnerCtl.value = "3";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum3(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum4",75,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.visible = true;
voCtl_InnerCtl.zIndex = 3;
voCtl_InnerCtl.value = "4";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum4(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum5",100,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.visible = true;
voCtl_InnerCtl.zIndex = 4;
voCtl_InnerCtl.value = "5";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum5(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum6",125,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.visible = true;
voCtl_InnerCtl.zIndex = 5;
voCtl_InnerCtl.value = "6";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum6(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum7",150,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.visible = true;
voCtl_InnerCtl.zIndex = 6;
voCtl_InnerCtl.value = "7";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum7(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum8",175,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.visible = true;
voCtl_InnerCtl.zIndex = 7;
voCtl_InnerCtl.value = "8";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum8(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum9",200,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.visible = true;
voCtl_InnerCtl.zIndex = 8;
voCtl_InnerCtl.value = "9";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum9(e); };
voCtl.addChild(voCtl_InnerCtl);
voCtl_InnerCtl = poPage.canvas.createControl("label","lblPageNum10",225,5,18,18);
voCtl_InnerCtl.tabIndex = 0;
voCtl_InnerCtl.visible = true;
voCtl_InnerCtl.zIndex = 9;
voCtl_InnerCtl.value = "10";
voCtl_InnerCtl.onclick = function(e) { page.onClick_lblPageNum10(e); };
voCtl.addChild(voCtl_InnerCtl);
}
poPage.canvas.appendControl(voCtl);
voCtl = poPage.canvas.createControl("output","optPageTCNoSearch",1,3,341,27);
voCtl.tabIndex = 0;
voCtl.zIndex = 3;
voCtl.value = "검색결과가 없습니다. 재조회 하시기 바랍니다.";
voCtl.formatType = "string";
voCtl.regFormat = null;
voCtl.textAlign = "center";
poPage.canvas.appendControl(voCtl);

};

};